# The title of your site
title: A Practical Learning Path for Security Analysts

# The theme for your site
theme: just-the-docs

# The URL for your site
url: "https://TerjeRu.github.io"

# The base URL for your site. This is CRITICAL.
baseurl: "/docs"

# Enable search
search_enabled: true

# Optional: Add a link to your repository in the navigation
aux_links:
  "View on GitHub": "https://github.com/TerjeRu/docs"

# Another optional setting, adds a "back to top" link
back_to_top: true
back_to_top_text: "Back to top"
